### ISSUE TITLE
[BLOCKER] Livechat widget breaks on mobile because of localStorage access

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#1015]
```
Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at Module.<anonymous> (https://messaging.vega-preprod.viasat.io/livechat/rocketchat-livechat.min.js?_=201903270000:1:12402)
    at n (https://messaging.vega-preprod.viasat.io/livechat/rocketchat-livechat.min.js?_=201903270000:1:110)
    at https://messaging.vega-preprod.viasat.io/livechat/rocketchat-livechat.min.js?_=201903270000:1:911
    at https://messaging.vega-preprod.viasat.io/livechat/rocketchat-livechat.min.js?_=201903270000:1:920
```

Perhaps there is a race condition where we are trying to access local storage before it is available?

**Comment by ear-dev** [comment]
@Shailesh351 can you add some information here about your findings to date?

We already made an attempt at disabling the logging on mobile, but that did not resolve the issue:  https://github.com/WideChat/Rocket.Chat.Livechat/pull/112   After we find the fix, we should remember to clean up this first attempt.

ISSUE:
So far we have not been able to reproduce the issue outside of actually using the my.viasat test application.

**Comment by Shailesh351** [comment]
## RCA
I tried a bunch of commits after each recent PRs and found that the issue was not because of logging, it was after this PR.
https://github.com/WideChat/Rocket.Chat.Livechat/pull/103

```
  //c722ae0c66748365b848ae76365701eba0f2a16e fails
  //68a53511f5b41f6ad5df5147f8a9f2f916320a03 fails
  //b73b3c8356347f3899e4b8beef8c05f9b94c311d works
  //e03905828f9692dc464b17136f4060857b0a7725 works
```

In that PR `store` was being used in the `widget.js`, which is like an entry-level file and localStorage is not available in that file.

I have created PR https://github.com/WideChat/Rocket.Chat.Livechat/pull/114 to fix the same. Thanks!
