### ISSUE TITLE
[Actions] Fix our workflow for weekly catchup

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#1028]
All the catchup actions are failing and it seems like a permissions issue maybe.

**Comment by ear-dev** [comment]
also needs refactor and improvements.

**Comment by Shailesh351** [comment]
@ear-dev The issue is with the default `GITHUB_TOKEN` in the workflow. It does not have the privilege to write. Even after specifying permissions in the workflow file, it was not working (https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/).

So to fix this issue we need to create a Personal Access Token and use that in the workflow. Below are the steps for the same,

- Create Personal Access Token from `Account Settings` -> `Developer Settings` 
-> `Personal Access Token` -> `Generate New Token` (https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token) 

- Add this token as a secret in every repo. `Repository Settings` -> `Secrets` -> `New repository secret`. Name it something which will be used in the workflow i.e `PAT`

- Replace `GITHUB_TOKEN` with `PAT` in the auto catchup workflow file. https://github.com/WideChat/Rocket.Chat/blob/develop_pwa/.github/workflows/auto_catchup.yml#L30

**Comment by ear-dev** [comment]
@Shailesh351 I have added the PAT secret and commited the change in the workflow to use it.....  but only in the Rocket.Chat repo so far.  I'm not sure the best way to test, i.e. manually trigger it.  Can you verify please if the PAT change worked?  Thanks

**Comment by Shailesh351** [comment]
@ear-dev Currently it is showing "Invalid workflow file" https://github.com/WideChat/Rocket.Chat/actions/runs/1708961612/workflow. I will create PR to update the workflow file for testing

**Comment by ear-dev** [comment]
Yeah, I realize that I misconfigured that, and then I reverted it.  Feel free to test any way that works.

**Comment by Shailesh351** [comment]
@ear-dev I have created this PR https://github.com/WideChat/Rocket.Chat/pull/1062. After this, we should be able to test the workflow from the actions tab. I have tested it on my own rocket chat fork

**Comment by ear-dev** [comment]
OK, looks good........  can you revert the manual trigger change please.  I'll add the secret to the other repos and make the PRs.... Thanks!

**Comment by Shailesh351** [comment]
Cool. Here's the PR for reverting https://github.com/WideChat/Rocket.Chat/pull/1064. Thanks!!
