### ISSUE TITLE
Dialogflow Events not being sent after escalated chat is closed, intermittent in prod - can't reproduce in uat

### ISSUE THREAD

**Issue by Shailesh351** [WideChat/Rocket.Chat#1071]

**Comment by chadgoss** [comment]
What we're seeing:
- chat is escalated
- escalation fails as no agents are online
- `neuraflash_escalate_unavailable` intent (or `neuraflash_escalate_error`) is supposed to be triggered, but isn't

as a result fulfillment isn't aware that the escalation failed, and is not creating/attaching a transcript and closing the case

**Comment by chadgoss** [comment]
@Shailesh351 we're seeing that issue quite a bit in prod, any thoughts on how we might instrument the SF app to get some clues?

Note, I do see it working as well in prod. Most of the time when escalation fails it's hitting `neuraflash_escalate_unavailable` properly

This is correct:
<img width="924" alt="Screen Shot 2022-01-27 at 4 42 31 PM" src="https://user-images.githubusercontent.com/9826215/151448487-37e8607f-b102-46ec-aab5-3b0ea4744673.png">


=============================================================================

This is incorrect - since fulfillment never gets the DF event notification that the escalation fails, we never update the transcript and close the case
<img width="743" alt="Screen Shot 2022-01-27 at 4 46 02 PM" src="https://user-images.githubusercontent.com/9826215/151448949-03762a68-28c7-42e6-ab2f-be6320829cc2.png">

**Comment by ear-dev** [comment]
@chadgoss do you think this is new behavior, or is it just something we haven't noticed before?  Any way to tell?

**Comment by chadgoss** [comment]
@ear-dev hard to say since we've had the bug in our backlog to mark failed escalations as such for a long time. Going back and tracking it down would be difficult.
