### ISSUE TITLE
[Livechat] Refactor setGuestPhone to remove entry upon empty string

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#1139]
We added setGuestPhone() to livechat so that we could set that with our test widget.  It turns out that the livechat data is persistent and stored on the server side, so we need a new method `unsetGuestPhone()` in order to have the ability to clear the number when we don't want to use it.

**Comment by ear-dev** [comment]
Design:  do not create an unset function....  factor the current function remove the telephoneNumber entry in mongodb if we send it an empty string. 
- we will adjust the test widget to always call setGuestPhone()

**Comment by AlexanderKanakis** [comment]
Updated PRs:
https://github.com/WideChat/Rocket.Chat.IntegrationTests/pull/3
https://github.com/WideChat/Rocket.Chat/pull/1142
https://github.com/WideChat/Rocket.Chat.Livechat/pull/141

Created `unsetGuestPhone` function, which is used on the IntegrationTest widget when the guest phone number is empty.

**Comment by Shailesh351** [comment]
@ear-dev As discussed in the meeting yesterday, because @AlexanderKanakis is currently away due to medical treatment I have created below PRs to fix this issue. Thanks!

Rocket.Chat: https://github.com/WideChat/Rocket.Chat/pull/1178
Rocket.Chat.Livechat: https://github.com/WideChat/Rocket.Chat.Livechat/pull/143

- To set visitor phone: `this.setGuestPhone(<phoneNumber>)`
- To unset visitor phone pass `''`/`null`/`undefined` or just blank as fn argument: `this.setGuestPhone()`/`this.setGuestPhone('')`

**Comment by ear-dev** [comment]
Thanks @Shailesh351 I will test as well....
