### ISSUE TITLE
[Save Chat] Figure out download permissions on mobile

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#1153]
This will require coordination with the myViasat team. 
- spec the requirements
- myViasat has to sign off on them.

Ios, Android

**Comment by ear-dev** [comment]
@Shailesh351 Can you please demo how MyViasat currently does download invoice on mobile?  I understand that it uses app storage and we'd like to understand the users experience.  Perhaps we do the same for transcript.....  

Issue:  Downloading to local storage requires elevated permissions that are currently not available in the app.

**Comment by ear-dev** [comment]
Solution:  Let's use the same methods that the myViasat app is currently using.  The file will open in a viewer, and it will be up to the visitor if they want to save or print it from there.  We want to avoid asking for permissions, since myViasat is doing it without new permissions. 

- will this work with a txt file?
- do we need to present pdf instead? - can we do this easily??

If possible we do not want to have a unique implementation for our downloads when the widget is inside the mvApp.

Changes will be in both repos.....  myViasat, Livechat

**Comment by Shailesh351** [comment]
MyViasat PR: https://git.viasat.com/ICAT/MyViasat/pull/1141

**Comment by Shailesh351** [comment]
Pending Items:
- Currently, this is not working on mobile browsers because `isMobile` does not differentiate between Mobile browsers and WebView. We will need to add additional conditions to check the webview.
- Currently, it is saving in `.txt` format, we want it in `.pdf` to make the UX as near as possible to MyViasat. And also opening the `.txt` file will open in the browser and from the browser, there is no direct way to save it. (Browser -> Share from three-dot menu) -> Print) which is bad UX.

@ear-dev  I'm looking into both of the pending items 👍

**Comment by Shailesh351** [comment]
@ear-dev Above Issues are now fixed. Save transcript now works with `.pdf`.

### Design
Instead of adding pdf generator library at client-side (Widget), which also makes loading widget slower. The library is added on the server-side.

`User Clicks Save Transcript` -> `Server generates pdf and passes it to client in base64 string` -> `Client decodes base64 to show pdf`

### PRs

Rocket.Chat: https://github.com/WideChat/Rocket.Chat/pull/1186
Rocket.Chat.LiveChat: https://github.com/WideChat/Rocket.Chat.Livechat/pull/140
Rocket.Chat.LiveChat.Test-App: https://github.com/WideChat/Rocket.Chat.Livechat.Test-App/pull/3

MyViasat: https://git.viasat.com/ICAT/MyViasat/pull/1141

**Comment by ear-dev** [comment]
@AlexanderKanakis can you test this in the Test-app please?
