### ISSUE TITLE
[Mobile App Android] [MV PR][BUG] The keyboard covers the transcript on some mobile devices

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#1163]
Currently the keyboard opens and covers the bottom portion of the transcript so that the visitor does not see the composer.

This is not an issue in IOS.

**Comment by csmith14** [comment]
This only seems to be reproducible in the Test-App -- When building and running the MyViasat app on an android virtual device, the keyboard and input are positioned correctly:
![Screen Shot 2022-06-22 at 1 47 54 PM](https://user-images.githubusercontent.com/27293306/175170373-74d5fec9-450d-45c9-9976-0d914f219172.png)

**Comment by ear-dev** [comment]
@csmith14 please add the link to the property in the myViasat repo that is designed to solve this problem.... to this story

**Comment by csmith14** [comment]
@ear-dev Since I will be out and am still working on this issue, I thought I’d send a breakdown of my current status before I leave.

For the issue of the keyboard covering the input field on some Android devices, I have found that changing the value of the ‘keyboardVerticalOffset’ ([here](https://git.viasat.com/ICAT/MyViasat/blob/dbd000f88e4ca2d22d6871fd2d6d1d47322d6a7e/packages/mobile/src/views/ContactUs/RocketChat.tsx#L32)) property higher on smaller/older devices fixes the issue. The docs for this property are [here](https://reactnative.dev/docs/keyboardavoidingview#keyboardverticaloffset). The doc states “This is the distance between the top of the user screen and the react native view” --  this leads me to think that if we were to calculate that value based on the view height and screen height, we could fix the overlap issue.

I have not found anything substantial regarding message scrolling when the keyboard first opens, but will continue to look into that when I return.

**Comment by csmith14** [comment]
PR for this story has been opened [here](https://git.viasat.com/ICAT/MyViasat/pull/1175)

**Comment by csmith14** [comment]
Original PR in MyViasat repo has been closed, new PR opened in the ICAT/mfe monorepo: https://git.viasat.com/ICAT/mfe/pull/212
