### ISSUE TITLE
A webhook to automatically prepare a catchup PR for us whenever RocketChat release a new version

### ISSUE THREAD

**Issue by kb0304** [WideChat/Rocket.Chat#316]

**Comment by shubhsherl** [comment]
Between new releases of RC, there are almost 30k lines of codes, and 1k file changes, which will make the PR hard to review, we may want to catchup weekly. I've created a [github action](https://github.com/shubhsherl/create-catchup-pr/) which we can use to create PRs using GitHub workflow, triggered weekly.
The `.yml` should be in the default branch. Since we are using `develop_pwa`, we can make that our default branch. Or pushing the `.yml` to `develop` branch will also do the job.
