### ISSUE TITLE
Fix sidebar background color.

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#356]
After the latest catchup merge we have lost the widechat sidebar background color.  It seems that color variables have been refactored a little bit, and I think that the var --sidebar-background might be new.

https://github.com/RocketChat/Rocket.Chat/search?q=--sidebar-background&unscoped_q=--sidebar-background&type=Code

**Comment by Shailesh351** [comment]
@ear-dev Looking into this issue.

**Comment by Shailesh351** [comment]
@ear-dev I debugged issue. Earlier `--sidebar-background` was referring to `--rc-color-primary`. But now it is referring to `--rc-color-primary-background`

So can you also set `--rc-color-primary-background` in the admin section?
admin -> Layout -> Colors -> Primary Background

**Comment by ear-dev** [comment]
@Shailesh351 this did not work unfortunately.

**Comment by Shailesh351** [comment]
@ear-dev As I can see from dev tools value of `--rc-color-primary-background` is not properly set.
<img width="862" alt="Screenshot 2020-07-18 at 9 11 28 AM" src="https://user-images.githubusercontent.com/18264684/87844079-1390c500-c8d7-11ea-948e-e3c144855f8a.png">

Can you make sure you set color using below popup? Otherwise it interprets it as expression(variable). Just click on the color bar in the left.
<img width="1676" alt="Screenshot 2020-07-18 at 9 13 26 AM" src="https://user-images.githubusercontent.com/18264684/87844101-65d1e600-c8d7-11ea-9cbe-616cdf9358fd.png">

**Comment by ear-dev** [comment]
Thanks @Shailesh351 I thought that I was doing just that...... and yet, now it seems to be working.

**Comment by Shailesh351** [comment]
Issue is resolved. So closing it.
