### ISSUE TITLE
"invalid room" error

### ISSUE THREAD

**Issue by chadgoss** [WideChat/Rocket.Chat#677]

**Comment by chadgoss** [comment]
<img width="388" alt="Screen Shot 2021-05-12 at 9 15 06 AM" src="https://user-images.githubusercontent.com/9826215/117981398-f7955e80-b302-11eb-97d3-4b1b7620237d.png">

**Comment by Shailesh351** [comment]
In the widget script
```
RocketChat(function () {
				const appName = "MyViasat";
				const token = "MyViasatToken";

				this.setCustomField("appName", appName);
				this.setCustomField("token", token);

				this.onChatStarted(() => {
					this.setCustomField("rAppName", appName);
					this.setCustomField("rToken", token);
				});
				this.registerGuest({
				 	name: "visitor Name",
				 	email: "sample@rocket.chat",
				});
			});
```

Instead of registerGuest method we need to use `this.setGuestName('visitor name');`, `this.setGuestEmail('sample@rocket.chat')` methods.

Suppose currently chat is going on and the user refreshes the page. In this case, this registerGuest call refreshes the visitor token, and the current chat is now associated with the old token.

And this causes `invalid-room` error.
