### ISSUE TITLE
[Investigate] Agent sneak peek not working in the salesforce console, escalated session on Mobile platform

### ISSUE THREAD

**Issue by chadgoss** [WideChat/Rocket.Chat#797]
In an escalated session, the agent should get a preview of what the user is typing. This is not working on iOS or Android. Confirmed in Production

**Comment by chadgoss** [comment]
this can be reproduced on the IOS simulator from xcode, follow the instructions at the VERY bottom of https://my-viasat-mobile.icat.viasat.io/ to install the app.

I was using iPhone 12 pro max - 14.4

**Comment by chadgoss** [comment]
I just tested this in production and the agent confirmed that they were only getting text when I hit enter. Sneak peak is not working on mobile. Both iOS and Android.

**Comment by ear-dev** [comment]
@Shailesh351 @bhardwajaditya  I just tested this on android and it worked for me, but did not work on web....  which is very odd because it is the exact opposite of what the Issue is reporting.  Can you verify as well please? 

We would like to characterize where we are now and create stories to fix sneak peak in all cases.  Thanks...

**Comment by Shailesh351** [comment]
@ear-dev It's working in my setup for all three platforms. On the web are you seeing it intermittently or persistently? 

Can you share with me the link to the salesforce console for pre-prod? I will check on pre-prod as well. Will it directly make me an agent using viasat.io login?

**Comment by ear-dev** [comment]
@csmith14 can you put the link to the PR in this Issue please?  Thanks...
