### ISSUE TITLE
[BUG] PWA sometimes needs refresh to see room messages

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#861]

**Comment by ear-dev** [comment]
@bhardwajaditya @Shailesh351 This is an issue we've seen in our PWA for a long time.......  do you have any thoughts about this?  Maybe just keep it in mind as a background task.....  if there is an easy solution I think it worth working on.  Thanks.

**Comment by bhardwajaditya** [comment]
@ear-dev I will have a look at this, the way we implemented prefetching of messages break it a bit. I will look into it parallely

**Comment by ear-dev** [comment]
Thanks @bhardwajaditya

**Comment by ear-dev** [comment]
@bhardwajaditya please summarize your findings and research how other apps handle our situation in regard to streams and long lived tabs.  We need a design recomendation. 

For the prefetching issue, please fix.

**Comment by bhardwajaditya** [comment]
We have two issues with PWA messages at present:
- The prefetching is broken due to upstream changes - **Will be fixed via another story**
- Upstream establishes new connection for messages on each load, whereas we maintain a socket connection for messages which when the app goes to sleep is broken and does not re establish on it's own till the time refresh is performed. - **TO BE INVESTIGATED**

**Comment by ear-dev** [comment]
@bhardwajaditya Peter is asking about the fix for this......  do you think the PR can be ready soon?  I'd like to prioritize this please. Thanks.

**Comment by bhardwajaditya** [comment]
@ear-dev PR is almost ready, will raise in an hour.
