### ISSUE TITLE
[Brazil] Menu Fix - Investigate combining messages from Dialogflow before passing them to the client (widget or whatsApp)

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#864]
example:  currently the menu from CX in whatsApp comes in as a series of unique messages.  in this case it would be nice if it was all in the same message/bubble.

Might be other use-cases?

CX only!

**Comment by stetak** [comment]
Below is an example response (sorry if the spacing is a bit mangled). But you can see each "responseMessage" has a "responseType" and "source". One option is that if a message has the same responseType and source as the previous message, concatenate those messages. So currently, the output is showing 5 messages:

```
The following data packages are available:

1GB for R$9,99

5GB for R$45,99

10GB for R$89,99

How many GB would you like to purchase?
```

And implementing this suggested change would only show 3 (the middle one containing all 3 plan options)

```
The following data packages are available:

1GB for R$9,99
5GB for R$45,99
10GB for R$89,99

How many GB would you like to purchase?
```

```
{
insertId: "4qdxx6c7yx"
jsonPayload: {
queryResult: {
advancedSettings: {
loggingSettings: {1}
}
currentPage: {2}
diagnosticInfo: {6}
intent: {2}
intentDetectionConfidence: 1
languageCode: "en"
match: {5}
parameters: {18}
redactedParameters: [1]
responseMessages: [
0: {
responseType: "ENTRY_PROMPT"
source: "WEBHOOK"
text: {
text: [
0: "The following data packages are available:"
]
}
}
1: {
responseType: "ENTRY_PROMPT"
source: "VIRTUAL_AGENT"
text: {
text: [
0: "1GB for R$9,99"
]
}
}
2: {
responseType: "ENTRY_PROMPT"
source: "VIRTUAL_AGENT"
text: {
text: [
0: "5GB for R$45,99"
]
}
}
3: {
responseType: "ENTRY_PROMPT"
source: "VIRTUAL_AGENT"
text: {
text: [
0: "10GB for R$89,99"
]
}
}
4: {
responseType: "PARAMETER_PROMPT"
source: "VIRTUAL_AGENT"
text: {
text: [
0: "How many GB would you like to purchase?"
]
}
}
]
text: "buy more"
webhookPayloads: [1]
webhookStatuses: [1]
}
responseId: "423d309c-c9b8-472b-87be-ee0d347a537a"
responseType: "FINAL"
}
labels: {2}
logName: "projects/viasat-chatbot-nlp/logs/dialogflow-runtime.googleapis.com%2Frequests"
receiveTimestamp: "2021-08-11T22:42:55.819157924Z"
resource: {2}
severity: "INFO"
timestamp: "2021-08-11T22:42:55.091485Z"
}
```

**Comment by AlexanderKanakis** [comment]
PR:
**Apps.Dialogflow**: https://github.com/WideChat/Apps.Dialogflow/pull/104

**Comment by stetak** [comment]
@AlexanderKanakis You are correct, according to https://cloud.google.com/dialogflow/cx/docs/reference/rest/v3/QueryResult the fields that I was asking you to use aren't actually available in the response message.

It sounds like you are using info from diagnosticInfo, which I think we should probably stay away from, since that field doesn't appear to be strictly defined.

I'm now thinking that we maybe we can control message concatenation with the partial payload handling. We have the option in DialogFlow CX to enable partial payloads on a payload-to-payload basis. It might be a good to put this ticket on hold for a bit and work on the partial responses, and then see what happens when we combine the two. If we can control message concatenation explicitly with the DailogFlow partial response setting, that would actually be way better than trying to use the response types.
