### ISSUE TITLE
[Livechat App Integration][MicroService Frontend] Design simple interface for embedding the widget into apps

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#900]
Currently the myViasat app team is maintaining a script.js that is used for managing and configuring the widget integration into their app.  It provides functionality we needed like custom fields, startup order, etc....

We would like to own this type of integration code in order to make it very simple for any app to embed our widget and to comply with our needs.  

We need to design how we can provide a simple interface for this purpose.  Maybe a library, or an SDK...... and it needs to be compatible with web and mobile apps.

**Comment by ear-dev** [comment]
Develop a React library that would handle all the functions the current js script from myViasat handles
Will iterate later over more flexible functionality

WebView/livechat_widget

Questions:
- design intialization parameters
  - Which parameters will be useful for the app developer (our client)
- where do we host a react library internally to viasat?

**Comment by ear-dev** [comment]
Eric,

Yeap you should definitely assume React, I recommend Next Js specifically, it’s React with a few extras added to it.

Best,
Joel Evans

On Sep 10, 2021, at 12:37 PM, Rosenthal, Eric <Eric.Rosenthal@viasat.com> wrote:

Hi Joel,
 
We’re doing some design thinking about this……  should we assume React?
 
It’s unclear if we have a use case on the short term roadmap, but quite likely before too long I might think….
 
e

**Comment by ear-dev** [comment]
Use cases:

- my.viasat (widget - mobile and web)

**Comment by ear-dev** [comment]
@Shailesh351 please describe your design here.....  we will run it by Joel.

**Comment by Shailesh351** [comment]
To create this micro service frontend for embedding widget in the apps, we will create `react library`.

This react library will be supported for both web and mobile using `react js and react native`.

This library will be maintained as a `Monorepo` to keep business logic same for web and mobile. It will be hosted somewhere as package(internal npm?), so that it can be imported and used in any App.

Initially we will develop to meet all the current requirements of MyViasat App. And later extend functionalities as needed.
