### ISSUE TITLE
[BUG] Sneaky input seen in production - two tab problem

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#918]
Chad and Aditya will try to debug...

Is there something about Prod???

**Comment by chadgoss** [comment]
<img width="934" alt="Screen Shot 2021-09-03 at 8 20 41 AM" src="https://user-images.githubusercontent.com/9826215/132004248-3e6ecab5-ec58-433a-b69d-36f394bf5a6b.png">


<img width="796" alt="Screen Shot 2021-09-03 at 8 21 12 AM" src="https://user-images.githubusercontent.com/9826215/132004293-c0345f86-4093-446e-862d-f7641300e8ae.png">


here's an example, the customer pretty clearly never saw that the agent had closed the chat, and just continues typing
what's odd, is that in the case:
- two different rooms are created, one for the first block, one for the second block
- when the second room is created, the sequence of payloads fulfillment receives are:
1) Welcome event received
2) text payload received immediately (before fulfillment can respond to the Welcome event), with text "I can't wait till then"


it's that second payload that we label as a new session with no welcome event, because we havent yet had a chance to respond to the first packet.

**Comment by ear-dev** [comment]
@bhardwajaditya if you are able to reproduce this, lets please try to figure out why we cannot reproduce in Prod.  Please document findings here.  Use latest SF.app

**Comment by ear-dev** [comment]
NOTE: We have two trigger events from the widget:
- click the icon starts new room
- send message to a room - starts new room if no room

Disable the second trigger?  Might cause issues down the road with a CX bot using widget.

**Comment by ear-dev** [comment]
@bhardwajaditya please describe your blunt force method of resolving this issue here.... thanks.

**Comment by bhardwajaditya** [comment]
When we send a message to a Livechat room, it checks for the RC room associated with the current chat. If there's no room then a new chat request is sent to RC server and the same sequence of actions as that of a room opening trigger occurs.

I propose that we block this manual way of room creation i.e. sending message to an empty room, and the only possible way to create a new room is via automatically fired trigger when we click on the chat icon.

Post this fix when such a situation arises that the trigger is not fired and the composer is enabled, sending a message won't create a new room instead it will disable the composer and will ask the user to create a new chat request since the existing one is already closed.

@ear-dev @chadgoss Thoughts?

**Comment by chadgoss** [comment]
@bhardwajaditya one thing we could do quickly is deploy an error log point to production in that case. We can then see if that lines up with the error condition we're seeing. Could you create a PR for that?

**Comment by bhardwajaditya** [comment]
@chadgoss done
https://github.com/WideChat/Rocket.Chat.Livechat/pull/105

**Comment by bhardwajaditya** [comment]
@chadgoss @ear-dev I have fixed this, but there are some design issues which will make it in this state as shown in the video below, but my fix would make sure that the new room problem is solved. We would also require the timeout PR that I raised, I saw few weird timeout cases in two tab scenarios.

https://drive.google.com/file/d/1L_nd12aHQTW7LcHQW5K1m8XW1ntQa9li/view?usp=sharing

**Comment by ear-dev** [comment]
@bhardwajaditya yeah, that state is a little weird.....  lets go over all of this in the meeting tomorrow.
