### ISSUE TITLE
[apps-cli] Include deploy date/time (when the app was deployed) in App along with version and commit hash

### ISSUE THREAD

**Issue by chadgoss** [WideChat/Rocket.Chat#941]

**Comment by ear-dev** [comment]
@ItzzRitik It does not seem like the keep alive on the widget story is a high priority at the moment from our stakeholders......  this one might be quick, can you grab this next please?  This applies to both our DF and SF.apps....  thanks

**Comment by itzzritik** [comment]
PR Raised:

1. [Rocket.Chat](https://github.com/WideChat/Rocket.Chat/pull/966)
2. [Apps Engine](https://github.com/WideChat/Rocket.Chat.Apps-engine/pull/37)

**Comment by ear-dev** [comment]
@Shailesh351 do you have time to review and test these PRs?  Thanks.

**Comment by Shailesh351** [comment]
@ItzzRitik I just noticed, In the Apps-Engine PR(https://github.com/WideChat/Rocket.Chat.Apps-engine/pull/37) you have updated the build file(.js) instead of the src file(.ts). And because of that, your changes are lost. If you are available can you create PR for AppsEngine with the fix, please?

@ear-dev FYI

**Comment by itzzritik** [comment]
@Shailesh351 
Oh, that's silly, Thanks for pointing.
I'll do it now!

**Comment by itzzritik** [comment]
@Shailesh351 
Here's the new PR -> [WideChat/Rocket.Chat.Apps-engine#40](https://github.com/WideChat/Rocket.Chat.Apps-engine/pull/40)
