### ISSUE TITLE
[BUG] Messages processed in order they are received broken in CX?

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#971]
In this case we are not seeing text0, even though the room gets closed. 

![image](https://user-images.githubusercontent.com/28864717/136963622-78b8cbd1-06ea-4971-bf91-f41db95b8604.png)

**Comment by ear-dev** [comment]
Possible cause:
The text can be delayed across the wire to Twilio (well understood issue)...  but the df_close_chat happens on the server side with no delay. 

So even though processed in correct order, race condition ensues, and the app side will always win.

**Comment by ear-dev** [comment]
Will partial responses make this a non issue?  Can we propose a fix in the meantime?

At the moment this only effects the deregistration flow as far as we know, and therefore not a super high priority yet, but we should have a strategy for a fix.

**Comment by bhardwajaditya** [comment]
@ear-dev the problem is how we process cx messages response object, we don't store them in the same order as they receive. We concat all the possible texts, actions are stored as they arrive. Once all the response messages are parsed, the concatenated text message is then added back. This messes up the order up a bit.

For example - 
if the response contains the following contents:
[ text, action, text]

Post our processing the order would be:
[ action, text] - Here text is concatenation of both the text messages in the original response


So this is not due to process message in same order fix, it processes them in order as it receives. It's a separate issue with parsing CX response from dialogflow

**Comment by ear-dev** [comment]
Fix: Only concatenate adjacent text.  Next text after an action starts a new concatenation.......  i.e. we continue to process the text after any action, as a new set of concatenated messages.

**Comment by bhardwajaditya** [comment]
@ear-dev fixed this and raised the PR
